# https://leetcode.com/problems/synonymous-sentences/solutions/430489/python-union-find/

class Solution:
    def generateSentences(self, synonyms: List[List[str]], text: str) -> List[str]:
        uf = {}
        
        def union(x, y):
            uf[find(y)] = find(x)
            
        def find(x):
            uf.setdefault(x, x)
            if uf[x]!=x:
                uf[x] = find(uf[x])
            return uf[x]
        
        # Using union-find to collect all the synonyms words.
        # After union find, all synonyms words will have a same root
        # which is find(word) as path compression is used in union find.  
        for a,b in synonyms:
            union(a, b)
        
        # Put all synonyms words in a list,
        # if the word doesn't have any synonyms words, put itself in the list.
        # E.g. [ ['I'], ['am'], ['happy', 'joy']]
        d = collections.defaultdict(set)
        for a, b in synonyms:
            root = find(a)
            d[root] |= set([a, b])
        txt = text.split()
        res = []
        for t in txt:
            if t not in uf:
                res.append([t])
            else:
                r = find(t)
                res.append(list(d[r]))
        
        # Use itertools.product to generate all the combinations.
        # Final results can be generated by " ".join and sorted.
        fin_res = [" ".join(sentence) for sentence in itertools.product(*res)]
        return sorted(fin_res)
        
